config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #topページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  #user新規登録
  resources :users, only: %i[new create]

  #ログイン
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #バイタル
  resources :vitals do
    resource :defecations, only: %i[create destroy]
    resources :comments, only: %i[create destroy],shallow: true
  end
  resource :profile, only: %i[show edit update]
  #既往歴
  resources :medical_histories, except: [:index, :show]
end

app/models/medical_history.rb
# == Schema Information
#
# Table name: medical_histories
#
#  id           :bigint           not null, primary key
#  disease_name :string           not null
#  in_treatment :boolean          not null
#  when_onset   :date             not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_medical_histories_on_user_id  (user_id)
#
class MedicalHistory < ApplicationRecord
  belongs_to :user

  validates :disease_name , presence: true
  validates :when_onset , presence: true
  validates :in_treatment, inclusion: {in: [true, false]}

  scope :is_during_treatment, -> (value){ where(in_treatment: value).order(when_onset: :asc) }
end

app/controllers/medical_histories_controller.rb
class MedicalHistoriesController < ApplicationController
  before_action :set_medical_history, only: %i[edit update]
  
  def new
    @medical_history = current_user.medical_histories.build
  end

  def create
    @medical_history = current_user.medical_histories.build(medical_history_params)
    if @medical_history.save
      redirect_to profile_path, success: t('defaults.message.created', item: MedicalHistory.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_created', item: MedicalHistory.model_name.human)
      render :new
    end
  end

  def edit; end

  def update
    if @medical_history.update(medical_history_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: MedicalHistory.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: MedicalHistory.model_name.human)
      render :edit
    end
  end

  def destroy
    medical_history = current_user.medical_histories.find(params[:id])
    medical_history.destroy!
    redirect_to profile_path, notice: '削除に成功しました'
  end

  private
  def medical_history_params
    params.require(:medical_history).permit(:disease_name,:in_treatment,:when_onset)
  end

  def set_medical_history
    @medical_history = current_user.medical_histories.find(params[:id])
  end
end

app/views/medical_histories/_form.html.haml
.container
  = link_to '戻る', profile_path, class: "btn btn-secondary btn-sm"
  = form_with(model: medical_history, local: true) do |f|
    = render 'shared/error_messages', object: f.object
    %div
      = f.label :disease_name, '●これまでにかかったことのある病気名', class: "medical_history_form"
    %div
      = f.text_field :disease_name, class: 'form-control'
    %div
      %p
        (例)糖尿病、高血圧、腎臓病、肝臓病、喘息、心臓疾患
        胃潰瘍、緑内障、脳疾患、がん(部位　)、その他
    %div.mt-3
      = f.label :in_treatment, '●治療中ですか', class: "medical_history_form"
    %div
      = f.radio_button :in_treatment, "true"
      = f.label :in_treatment, 'はい'
      = f.radio_button :in_treatment, "false"
      = f.label :in_treatment, 'いいえ'
    %div.mt-3
      = f.label :when_onset, '●いつ頃ですか', class: "medical_history_form"
    %div
      = f.date_field :when_onset, class: 'form-control'
    = f.submit '保存', class: 'btn-log'

app/views/medical_histories/_medical_histories.html.haml
.container
  .medical_histories
    %input#tab-one{:name => "tabs", :type => "checkbox"}/
    %label{:for => "tab-one"} 既往歴
    .medical_histories_content
      %p
        - if @medical_histories.exists?
          = render @medical_histories
  .medical_histories
    %input#tab-two{:name => "tabs", :type => "checkbox"}/
    %label{:for => "tab-two"} 現病歴
    .medical_histories_content
      %p
        - if @current_medical_history.exists?
          = render  @current_medical_history

app/views/medical_histories/_medical_history.html.haml
.card.w-75.mx-auto
  .container
    .disease_name.medical_histories_edit
      = medical_history.disease_name
      .dropdown
        = image_tag "actions.svg",class: 'dropbtn',size: '30x30'
        .dropdown-content.mini
          = link_to '編集する',edit_medical_history_path(medical_history)
          = link_to '削除する',medical_history_path(medical_history),data:{method: 'delete',confirm:'本当に削除してもよろしいですか？'}
    %br
    発症時期: #{l(medical_history.when_onset, format: :default)}
    -if current_user.birthday.present?
      (#{medical_history.when_onset.year - current_user.birthday.year}歳)

app/views/medical_histories/edit.html.haml
= render 'form',medical_history: @medical_history

app/views/medical_histories/new.html.haml
= render 'form',medical_history: @medical_history