config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #topページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  #user新規登録
  resources :users, only: %i[new create]

  #ログイン
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #バイタル
  resources :vitals do
    resource :defecations, only: %i[create destroy]
    resources :comments, only: %i[create destroy],shallow: true
  end
  resource :profile, only: %i[show edit update]
  #既往歴
  resources :medical_histories, except: [:index, :show]
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-danger#error_messages
    %ul.mb-0
      - object.errors.full_messages.each do |message|
        %li= message

app/views/shared/_flash_message.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}
    = message

app/views/shared/_footer.html.haml
.container.py-3
  .row
    .col-12
      .text-center.footer_text
        = image_tag "ojisan.png", size: "50x50"
        .footer_balloon
          %p
            = link_to "利用規約", terms_path, class:"footer-text"
            \/
            \#{link_to "プライバシーポリシー", privacy_path, class:"footer-text"}
        .copyright
          %p Copyright © 2023 バイタル日記

app/views/shared/_header.html.haml
%body
  %header#header.header
    .header_logos
      %p.header_pageTitle
        - if logged_in?
          = link_to  vitals_path do
            = image_tag 'ojisan.png', size: "60x60"
        - else
          = link_to  root_path  do
            = image_tag 'ojisan.png', size: "60x60"
    - if logged_in?
      .openbtn
        %span
        %span
        %span
      %nav#g-nav
        #g-nav-list
          %ul
            %li= link_to 'Top', root_path, class: 'dropdown-item'
            %li= link_to 'Mypage', profile_path
            %li= link_to 'Vital', vitals_path, class: 'dropdown-item'
            %li= link_to t('defaults.logout'), logout_path, method: :delete , class: 'dropdown-item'
    - else
      = link_to "ログイン", login_path ,class: 'header_loginBtn'
  = javascript_pack_tag 'toggle'

app/views/shared/error_messages.html.erb
<% if object.errors.any? %>
  <div class= "alert alert-danger">
    <ul class= "mb-0">
      <% object.errors.full_messages.each do |message|%>
        <li><%= message%></li>
      <% end %>
    </ul>
  </div>
<% end %>