config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #topページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  #user新規登録
  resources :users, only: %i[new create]

  #ログイン
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #バイタル
  resources :vitals do
    resource :defecations, only: %i[create destroy]
    resources :comments, only: %i[create destroy],shallow: true
  end
  resource :profile, only: %i[show edit update]
  #既往歴
  resources :medical_histories, except: [:index, :show]
end

app/models/vital.rb
# == Schema Information
#
# Table name: vitals
#
#  id                :bigint           not null, primary key
#  day               :datetime         not null
#  high_bp           :integer          not null
#  low_bp            :integer          not null
#  oxygen_saturation :integer          not null
#  pulse             :integer          not null
#  temperature       :float            not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :bigint           not null
#
# Indexes
#
#  index_vitals_on_user_id  (user_id)
#
class Vital < ApplicationRecord
  belongs_to :user
  has_many :defecations, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :day , presence: true
  validates :high_bp , presence: true
  validates :low_bp , presence: true
  validates :pulse , presence: true
  validates :temperature , presence: true
  validates :oxygen_saturation, presence: true, numericality: { greater_than_or_equal_to: 90 }

  #検索一日検索
  scope :search_information, -> (keyword){
    where(day: keyword.in_time_zone.all_day)
  }


  #排便機能で使う#3日間で便秘気味かどうか
  scope :vital_three_days, ->{ where(day: 2.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  
end

app/controllers/vitals_controller.rb
class VitalsController < ApplicationController
  before_action :set_vital, only: %i[show edit update]

  def index
    @keyword = params[:keyword]&.strip || ''
    @vitals = current_user.search_vitals(@keyword).page(params[:page])
    #便秘機能
    @constipation = current_user.user_constipation
  end

  def show
    @comment = Comment.new
    @comments = @vital.comments
  end

  def new
    @vital = current_user.vitals.build
  end

  def create
    @vital = current_user.vitals.build(vital_params)
    if @vital.save
      redirect_to vital_path(@vital), success: t('defaults.message.created', item: Vital.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_created', item: Vital.model_name.human)
      render :new
    end
  end

  def edit; end

  def update
    if @vital.update(vital_params)
      redirect_to vital_path(@vital), success: t('defaults.message.updated', item: Vital.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Vital.model_name.human)
      render :edit
    end
  end

  def destroy
    vital = current_user.vitals.find(params[:id])
    vital.destroy!
    redirect_to vitals_path, success: t('defaults.message.deleted', item: Vital.model_name.human)
  end

  private

  def set_vital
    @vital = current_user.vitals.find(params[:id])
  end

  def vital_params
    params.require(:vital).permit(:temperature,:high_bp,:low_bp,:pulse,:oxygen_saturation,:day)
  end
end

app/views/vitals/_form.html.haml
.container
  = link_to '戻る', :back, class: "btn btn-secondary btn-sm"
  = form_with(model: vital, local: true) do |f|
    = render 'shared/error_messages', object: f.object
    %div
      = f.label :day, '計測日'
    %div
      = f.datetime_field :day, class: 'form-control'
    %div
      = f.label :temperature, '体温(度)'
    %div
      = f.text_field :temperature, class: 'form-control'
    %div
      = f.label :high_bp, '収縮期血圧(上の血圧mmHg)'
    %div
      = f.text_field :high_bp, class: 'form-control'
    %div
      = f.label :low_bp, '拡張期血圧(下の血圧mmHg)'
    %div
      = f.text_field :low_bp, class: 'form-control'
    %div
      = f.label :pulse , '脈拍数(回/分)'
    %div
      = f.text_field  :pulse , class: 'form-control'
    %div
      = f.label :oxygen_saturation, '酸素飽和度(%)'
    %div
      = f.text_field :oxygen_saturation, class: 'form-control'
    = f.submit  class: 'btn-log'

app/views/vitals/_new_btn.html.haml
= link_to new_vital_path do
  .float_btn
    %i.fa.fa-plus

app/views/vitals/_vital.html.haml
.card
  .card_vital.container
    .dropdown
      = image_tag "actions.svg",class: 'dropbtn'
      .dropdown-content.mini
        = link_to '編集する',edit_vital_path(vital)
        = link_to '削除する',vital_path(vital),data:{method: 'delete',confirm:'本当に削除してもよろしいですか？'}
    = link_to vital_path(vital) do
      %table.table.table-hover
        %thead
          %tr
            %th 体温
            %th 血圧(上)
            %th 血圧(下)
            %th 脈拍
            %th 酸素飽和度
            %th{:colspan => "3"}
        %tbody
          %tr
            %td{:class => "#{vital.check_temprature}"}= vital.temperature
            %td{:class => "#{vital.check_high_bp}"}= vital.high_bp
            %td{:class => "#{vital.check_low_bp}"}= vital.low_bp
            %td{:class => "#{vital.check_pulse}"}= vital.pulse
            %td{:class => "#{vital.check_oxygen_saturation}"}= vital.oxygen_saturation
  .vital{:id => "vital_#{vital.id}"}
    .card_detail
      .card_content
        コメント数(#{vital.comments.count})
        .card_feces.feces-btn
          = render 'defecations/defecation', vital: vital
        .card_day
          %p= l(vital.day, format: :short)

app/views/vitals/edit.html.haml
= render 'form', vital: @vital

app/views/vitals/index.html.haml
.container
  = render 'commons/search'
  #constipation
    = render 'defecations/constipation', constipation: @constipation
  = render @vitals
  = render 'new_btn'
  = paginate @vitals

app/views/vitals/new.html.haml
= render 'form', vital: @vital

app/views/vitals/show.html.haml
.container
  = link_to "一覧へ",vitals_path, class: "btn btn-secondary btn-sm mb-2"
  %br
  = render 'vital', vital: @vital
  .vital
    / コメントエリア
    = render 'comments/comments', { comments: @comments }
    / コメントフォーム
    = render 'comments/form', { vital: @vital, comment: @comment }