config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #topページ
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  #user新規登録
  resources :users, only: %i[new create]

  #ログイン
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  #バイタル
  resources :vitals do
    resource :defecations, only: %i[create destroy]
    resources :comments, only: %i[create destroy],shallow: true
  end
  resource :profile, only: %i[show edit update]
  #既往歴
  resources :medical_histories, except: [:index, :show]
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to vitals_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/views/user_sessions/new.html.haml
.container
  %h1= t '.title'
  = form_with url: login_path, local: true do |f|
    .form-group
      = f.label :email , User.human_attribute_name(:email)
      = f.text_field :email, class: 'form-control'
    .form-group
      = f.label :password , User.human_attribute_name(:password)
      = f.password_field :password, class: 'form-control'
    .actions
      = f.submit  (t '.title'), class: 'btn btn-log'
  .text-center
    = link_to (t '.to_register_page'),new_user_path